### ISSUE TITLE
Should AWS's DynamoDB be added?

### ISSUE THREAD

**Issue by csterritt** [255kb/stack-on-a-budget#109]
The documentation is unclear:

> As part of AWS’s Free Tier, AWS customers can get started with Amazon DynamoDB for free. DynamoDB customers get 25 GB of free storage, as well as up to 25 write capacity units and 25 read capacity units of ongoing throughput capacity (enough throughput to handle up to 200 million requests per month) and 2.5 million read requests from DynamoDB Streams for free.

I can't tell if the phrase "AWS's Free Tier" refers to the "some things free for the first year" only, or not.

Later, in the pricing example, they write:

> If you haven’t used up your free tier allotment (25 write capacity units, 25 read capacity units, 2.5 million Streams read requests, 25 GB of storage), you can run this application for free on DynamoDB.

This seems to indicate an ongoing free amount.  I'm (well) outside my "free tier" first year, but I'm not currently using DynamoDB for anything.

Anyone who has used DynamoDB extensively care to comment on their actual costs?  I'll have something going in a few weeks, so I can comment by then.

**Comment by Lusitaniae** [comment]
> As part of AWS’s Free Tier, AWS customers can get started with Amazon DynamoDB for free. 
This says it belongs to the first year for free thing, the Free Tier program.

The free tier allotment probably should cost about 30$ a month afterwards.

**Comment by ihamza** [comment]
It mentioned there https://aws.amazon.com/free/
that  AWS Free Tier (Non-expiring Offers): include 
> Amazon DynamoDB free tier 
> Enough to handle up to 200M requests per month. 
> Does not expire at the end of your 12 month AWS Free Tier term.

**Comment by csterritt** [comment]
@Lusitaniae @ihamza Thanks!  That's good to know.  I'll do a pull request shortly if no one else has.

**Comment by csterritt** [comment]
Created a pull request for this.
