### ISSUE TITLE
Would "special" plans be considered?

### ISSUE THREAD

**Issue by huanga** [255kb/stack-on-a-budget#13]
Thinking specifically about Mailgun's Google Cloud Platform promo: http://www.mailgun.com/google

If so, I can send a PR for that.

**Comment by 255kb** [comment]
Has it any time limitation? If not I will add this point to Mailgun's description, could be good to know!

**Comment by huanga** [comment]
I am not aware of any time restriction. I've been on the plan for about a year now and it is still kicking!

**Comment by 255kb** [comment]
Added!
