### ISSUE TITLE
add incapsula to cdn providers

### ISSUE THREAD

**Issue by Lusitaniae** [255kb/stack-on-a-budget#138]
Incapsula also offers a free plan for a service in the likes of Cloudflare. 
Focus on the application firewall, but includes cdn and optimization stuff.
https://www.incapsula.com/pricing-and-plans.html

**Comment by rjoydip** [comment]
@Lusitaniae does't have any free plan although `FREE TRIAL` for `ENTERPRISE` and other `trial` is for either `BUSINESS` or `PRO`

**Comment by Lusitaniae** [comment]
I remember using free plan before, seems to be hidden now...

I can find it here
https://www.incapsula.com/pricing-and-plans.html

Use our plan advisor >
Select CDN

It will show up the free plan and sign up button

**Comment by rjoydip** [comment]
@Lusitaniae when i select `Use our plan advisor` then only `Bad bot mitigation` is now free others add-ons are paid

**Comment by Lusitaniae** [comment]
So

it’s enough to be added to the CDN category
