### ISSUE TITLE
Add chat for website

### ISSUE THREAD

**Issue by AlexSenchenko** [255kb/stack-on-a-budget#143]
Hi,

Could you please add smth like intercom.com?

**Comment by rjoydip** [comment]
Hi @AlexSenchenko `intercom.com` can not be added because of there free tier is for only 14 days. Please check [excluded-services](https://github.com/255kb/stack-on-a-budget/blob/master/pages/excluded-services.md#list-of-excluded-services)

**Comment by 255kb** [comment]
hi, 
@AlexSenchenko Intercom is really good but the point of this list is to deploy small project in prod-like environments without paying. So time limited trials are exluded.
