### ISSUE TITLE
Add ostr.io

### ISSUE THREAD

**Issue by dr-dimitru** [255kb/stack-on-a-budget#152]
### ostr.io

[Pricing page](https://ostr.io/info/pricing) /  [free for Open Source](https://ostr.io/info/built-by-developers-for-developers#free-for-opensource-community) projects

- *Free tier*: up to 240 prerenders, 400 monitoring checks, 800 web-analytics requests, 400 web-CRON requests
- *Pros*: simple and easy to use, "one click" setup for Monitoring and Domains Protection, Prerendering  supports ES6 (ECMAScript 2015) 
- *Limitations*: No limits
- *Exceeding the free tier*: need to pay, Domain Names Protections continues to work as it's free for all accounts on all plans

----

Hello,

We're offering free usage (*no usage/features limits*) for [Open Source](https://ostr.io/info/built-by-developers-for-developers#free-for-opensource-community) projects.

With a free tier for all new accounts:
__Hobby__ plan:
 - Prerendering: 240 renders
 - Monitoring: 400 checks
 - Web-Analytics: 800 requests
 - Web-CRON: 400 requests
 - Domain name, DNS & SSL protection: free, no limits

__Pro__ plan:
 - Prerendering: 60 renders
 - Monitoring: 100 checks
 - Web-Analytics: 200 requests
 - Web-CRON: 100 requests
 - Domain name, DNS & SSL protection: free, no limits

__Business__ plan:
 - Prerendering: 30 renders
 - Monitoring: 50 checks
 - Web-Analytics: 100 requests
 - Web-CRON: 50 requests
 - Domain name, DNS & SSL protection: free, no limits

Links:
 - [Pricing page](https://ostr.io/info/pricing)
 - [About Prerendering](https://ostr.io/info/prerendering)
 - [About Monitoring](https://ostr.io/info/monitoring)
 - [About Domain Names Protection](https://ostr.io/info/domain-names-protection)
 - [About Web-Analytics](https://ostr.io/info/web-analytics)
 - [About Web-CRON](https://ostr.io/info/web-cron)

The main question is will it be okay to add this service to every matching category?

**Comment by rjoydip** [comment]
@dr-dimitru [ostr.io](https://ostr.io/) not responding

**Comment by rjoydip** [comment]
Hi @255kb [ostr.io](https://ostr.io/) not responding you can check and close this issue

**Comment by 255kb** [comment]
@rjoydip it's responding for me

**Comment by dr-dimitru** [comment]
@rjoydip it's responding. Monitoring has no alerts for 4-5pm (*for a whole day actually*).
Where are you accessing from?

**Comment by rjoydip** [comment]
@dr-dimitru i am accessing from INDIA.

**Comment by dr-dimitru** [comment]
@rjoydip weird. Good it's available today. Have you get an error message or code?

**Comment by rjoydip** [comment]
I didn't saw error message tomorrow. But now site is responding
