### ISSUE TITLE
is azure-costs.com a good fit?

### ISSUE THREAD

**Issue by dantheother** [255kb/stack-on-a-budget#180]
Just wondering if https://azure-costs.com/ would be a good addition to this most excellent repo. If it is, I'm happy to raise a PR to add it into whichever category you suggest.

> Azure Cloud Cost Management & Optimization made easy

The free tier offers 2 months data retention, free forever.

_I'm not affiliated with them in any way, just found the tool when trying to discover why one of our azure subscriptions tripled in price._

**Comment by 255kb** [comment]
Hey, nice tool, why not create a new category "Cloud tools", or "Cloud management tools"? 
Feel free to submit a new PR 😃 
(Do not forget to add titles to the tables of contents, in alphabetical order.)
Thank you!
