### ISSUE TITLE
Add hoppscotch.io to API testing tools

### ISSUE THREAD

**Issue by liyasthomas** [255kb/stack-on-a-budget#205]
### Hoppscotch
[hoppscotch.io](https://hoppscotch.io) - A free, fast and beautiful API request builder (web alternative to Postman) used by 75k+ developers.

GitHub: https://github.com/hoppscotch/hoppscotch

Free tier: Unlimited sync for History, Collections, Environments.
Pros: GitHub/Google sign-in, self-hostable, open-sourced, Proxy mode, online web app.
Limitations: Requires Browser extension to test endpoints served locally.

**Comment by 255kb** [comment]
Hi @liyasthomas 
This is indeed a very useful tool, but this list is rather for SaaS products (app deployment, static hosting, email sending, etc). I don't think it would really fit.
