### ISSUE TITLE
Add repl.it to hosting

### ISSUE THREAD

**Issue by AgeOfMarcus** [255kb/stack-on-a-budget#206]
[repl.it](https://repl.it) is an online IDE - https://repl.it/site/about

Free tier: Unlimited Apps, Capped speeds, can keep your app running with uptimerobot.com

Paid: Keep your app running the official way, faster processing, private repls

I use it to run various discord and reddit bots, and websites

**Comment by 255kb** [comment]
While this is an interesting tool, this list is focusing on Saas products helping you deploy an app for free. Developer tools are not included.

**Comment by AgeOfMarcus** [comment]
I would say it belongs as it helps you host on a budget, or for free. I
host most of my websites and servers on there for free.
