### ISSUE TITLE
Add Gearhost database hosting

### ISSUE THREAD

**Issue by tpluscode** [255kb/stack-on-a-budget#21]
Free DB is limited to 10 MB only. Is that too restricting?

There is also $5 option with 1GB storage for MySQL and MS SQL. Or do only free tiers qualify to this list?

**Comment by 255kb** [comment]
hi, thanks for the contribution!
Only free tiers qualify for this list. However, even if it is limited in size it can be added there, as soon as it is still usable of course.

**Comment by tpluscode** [comment]
Depends on whether 10 MB can be called usable ;)

**Comment by 255kb** [comment]
yeah sure, it reminds me of Redis Cloud with 30Mb free, but it is still usable/enough in Redis case. 
But maybe it worth mentioning the service, and the limitation, because it is the first MySQL free tier I see :).

**Comment by tpluscode** [comment]
Hm, actually 10 megabytes is for MS SQL. MySQL is only 5 MB :(

**Comment by 255kb** [comment]
Ok, let's mention it. 
I have a side project with some hundreds of users and after years it is still not more than some Mb, so it could be still good to host a side project.
