### ISSUE TITLE
Add docevent.io

### ISSUE THREAD

**Issue by discobean** [255kb/stack-on-a-budget#211]
This has a free tier to host a FTP / sftp service.  I'm not sure where it would fit best in the groups.

There are limitations on the amount of data you can transfer.  But for general requirements to get an FTP or sftp server up and running it works great to get going.

It also requires an S3 or Azure backend (it connects FTP or sftp -> S3), but these can be also in a free tier.

docevent.io
[pricing page](https://docevent.io/pricing/)

Free tier: Lets you transfer 200MB of FTP or sftp data, and 5000 operations, 5 accounts/users max
Pros: Free ftp and sftp server, 3 regions, us-east-1, eu-west-1, ap-southeast-2, don't need to host any servers
Limitations: The backend is your own S3 (or Azure Blob/Files or GCP) bucket, but this can also be free
Exceeding the free tier: You can no longer login to the FTP service if you go over your free tier allowance

**Comment by 255kb** [comment]
I will add it to Static hosting like S3. 
Thanks for the contribution 👍
