### ISSUE TITLE
Oracle Cloud Free Tier

### ISSUE THREAD

**Issue by strawmanninen** [255kb/stack-on-a-budget#215]
https://www.oracle.com/cloud/free/#always-free

- Free tier: 2VMs with 1GB RAM, 2 Oracle Database VMs with 20GB storage, 2 Block Volumes with 100GB total, 10GB Object Storage, 10GB Archive Storage
- Pros: Load balancer, Monitoring, decent selection of pre-built OS images
-  Limitations: 10TB Outbound Bandwidth per month
- Exceeding the free tier: Service continues to work, can't exceed free tier

**Comment by 255kb** [comment]
Thanks, added!
