### ISSUE TITLE
Add Sauce Labs

### ISSUE THREAD

**Issue by tpluscode** [255kb/stack-on-a-budget#23]
Does free-for-open-source also qualify?

**Comment by 255kb** [comment]
Yes, it qualifies. 
I already added Travis CI for example, or Zeit Now which are both free for open source and/or expose source of the app, which may be ok for side projects especially if you are already publicly hosting your code on GitHub

**Comment by tpluscode** [comment]
Which category would Sauce Labs fit into?

**Comment by 255kb** [comment]
Maybe a new "App testing" category?
