### ISSUE TITLE
Sendgrid free account is not trial limited

### ISSUE THREAD

**Issue by senko** [255kb/stack-on-a-budget#230]
Thank you for compiling this list!

Small correction regarding Sendgrid:  sendgrid is listed as *the free tier has been limited to 30 days* in `pages/excluded-services.md`

That's not correct, as their free account is limited to 100 emails/day, but is not time-limited. See: https://sendgrid.com/pricing/

Quoting from description of the Free plan on that page (emphasis mine):

> Try it out! Integrate fast and explore features with 100 emails/day **forever**.

**Comment by 255kb** [comment]
Thanks for the info, I added it back
