### ISSUE TITLE
Add SuperTokens - User authentication platform [Open-Source + Cloud]

### ISSUE THREAD

**Issue by makeitcount** [255kb/stack-on-a-budget#278]
SuperTokens
* [Self-hosted Open-Source](https://github.com/supertokens/supertokens-core)
* [Hosted cloud solution](https://supertokens.com/) | [Pricing](https://supertokens.com/pricing)

**Free tier:** Self-hosted version is free forever with authentication for unlimited users. The hosted cloud solution is free up to 5K monthly active users.
**Pros:** Covers all primary methods of authentication and session management(including email/password, social, JWT, oAuth, etc.), lowest vendor lock-in, pre-built UI, quick to implement, easy to customize, feature segmentation
**Limitations:** None
**Exceeding the free tier:** (Applicable to hosted cloud solution only) You can switch to self-hosted version without any limitations or you can upgrade to increase the monthly active users support

**Comment by makeitcount** [comment]
Should I create PR for this?

**Comment by 255kb** [comment]
That would be great, thanks!
