### ISSUE TITLE
New website : Alwaysdata

### ISSUE THREAD

**Issue by xxloubexx** [255kb/stack-on-a-budget#299]
I used in the past [Alwaysdata](https://www.alwaysdata.com/en/) which is a cool website for web and database hosting.

There is a free plan : 100MB free for life.

Pros : Unlimited sites and applications (are supported Node.js, Python, PHP, Ruby, Elixir, Java, Deno and .NET), full SSL support, create schedules tasks, automatic backups each day with a retention of 30 days, unlimited domains and emails.

I think this website will be usefull for many people.

**Comment by 255kb** [comment]
@xxloubexx Could you submit a PR? Thanks :)
