### ISSUE TITLE
Free Image generation API 

### ISSUE THREAD

**Issue by Metim0l** [255kb/stack-on-a-budget#301]
Hello! I've created my own completely free image generation api. Thought you might be interested in adding it to your list. There are many different models of stable dufusion available. Here is the link: https://github.com/Metim0l/VisionCraft

**Comment by 255kb** [comment]
Hi, while this is a great achievement, I'm not sure your tool has its place here. The list is focused on services with free tiers ready for use in production. People must be confident that the tool will be around for a while, with an acceptable uptime (for a free tier), that the free tier is here to stay too, etc.
It's not a criticism but your tool looks more like a hobby project for now. Should it evolve we can surely reconsider!
