### ISSUE TITLE
StartSSL Free Certificate

### ISSUE THREAD

**Issue by niutech** [255kb/stack-on-a-budget#34]
You can get a [StartSSL Free](https://www.startssl.com/Support?v=1) Class 1 certificate for your domain or email.

**Comment by as-com** [comment]
Firefox will likely stop trusting StartSSL: https://wiki.mozilla.org/CA:WoSign_Issues (StartCOM was bought by WoSign)

**Comment by vintagesucks** [comment]
Chrome [will too](https://security.googleblog.com/2016/10/distrusting-wosign-and-startcom.html):

> ​Beginning with Chrome 56, certificates issued by WoSign and StartCom after October 21, 2016 00:00:00 UTC will not be trusted.

**Comment by niutech** [comment]
It's a pity since many people (and me) are using StartSSL certificates 😞

**Comment by vintagesucks** [comment]
@niutech Give [Let’s Encrypt](https://letsencrypt.org/) a try. 

> Let’s Encrypt is a free, automated, and open Certificate Authority.

Major Sponsors include Mozilla and Chrome.

**Comment by niutech** [comment]
@vintagesucks Thanks, but it requires me to regenerate a new cert every 3 months and not every cPanel has a plugin for it.
