### ISSUE TITLE
Free-for-dev dublicate?

### ISSUE THREAD

**Issue by G07cha** [255kb/stack-on-a-budget#36]
Hi, 

First of all, thanks for making seeking suitable service easier for everyone!

But there is another repository exists named [free-for-dev](https://github.com/ripienaar/free-for-dev) with extremely similar content, so I'm just thinking, what if you will help to make "free-for-dev" repo better rather then doing similar work in another repository it might be more effective.

I personally like current pros/cons structure, it could be transferred to the free-for-dev repo I think.

**Comment by 255kb** [comment]
Hi, thanks :) 
I did not know about free-for-dev repository until today, I will consider this. 
Also, as you noticed my goal was to add enough details in the repo so users can actually make a decision
