### ISSUE TITLE
Cloud9

### ISSUE THREAD

**Issue by NicolasLoew** [255kb/stack-on-a-budget#40]
C9.io
Free tier: App Hosting (Node/Webstack/WordPress..)
Pros: Decent power for free plans + fair upgrades. Own subdomain. Web IDE + Console.
Limitations: SSH access but no root.

**Comment by 255kb** [comment]
Thanks, will try to integrate this in the coming days :)

**Comment by NicolasLoew** [comment]
Haha glad to be able to contribute :)

**Comment by 255kb** [comment]
solved
