### ISSUE TITLE
db hosting: Cloudant

### ISSUE THREAD

**Issue by aeosynth** [255kb/stack-on-a-budget#42]
https://cloudant.com/product/pricing/

free tier: $1/gb/month, free if under $50/month

limitations: A credit card is required after the 30 day trial period is over

**Comment by aduth** [comment]
+1 to Cloudant. I use it for [my own side-project app](https://github.com/aduth/regimen) and it's a great free CouchDB solution, particularly for those like me using [PouchDB](https://pouchdb.com/) and wanting cloud persistence.

>limitations: A credit card is required after the 30 day trial period is over

I wasn't aware of this and it doesn't appear that I have a credit card on file with them, despite using their service for upwards of a year now. Maybe it's not enforced?

**Comment by aeosynth** [comment]
i don't currently use them, all i know is what's written on their site

**Comment by aduth** [comment]
This appears to be closed by #85 @255kb @michelemauro

**Comment by aeosynth** [comment]
neat, closing
