### ISSUE TITLE
Add mailtrap as fake SMTP server

### ISSUE THREAD

**Issue by eusonlito** [255kb/stack-on-a-budget#44]
Mailtrap

https://mailtrap.io/

Provides a fake SMTP server for your development team to test, view and share emails sent from the pre-production environments and test with real data without the risk of spamming real customers.

The Free Plan is more than enough to test any app.

Free tier: unlimited time
Pros: Easy to setup
Limitations: 1 inbox, 50 messages per inbox, 2 emails/sec per inbox

**Comment by 255kb** [comment]
Thanks, I will probably add this in the "Misc" part

**Comment by ponce11** [comment]
![screenshot_2017-02-28-08-39-53](https://cloud.githubusercontent.com/assets/25211817/23414642/857b2706-fd91-11e6-8a3d-6da7afc2cf8c.jpg)

**Comment by DuckThom** [comment]
Sorry for the commit spam. For some reason `git commit --amend --reset-author` does not change the author to the one I set in `user.email` (which has worked in the past) ...
