### ISSUE TITLE
Openshift removed 3 free tiers for unlimited amount of time for the new accounts

### ISSUE THREAD

**Issue by Prashanth-Nelli** [255kb/stack-on-a-budget#49]
Old users who have signed up prior to August 1st can still use this feature.
But new sign ups are removed.
Currently you can only try openshift 3 for 30 days.

[http://stackoverflow.com/questions/38744385/openshift-3-free-version-for-small-scale-apps](reference)

**Comment by 255kb** [comment]
Your link is broken, and I cannot find any clear information about this on their website. Any other source I could add in the service description? Thanks
