### ISSUE TITLE
Add short description below service names

### ISSUE THREAD

**Issue by ghost** [255kb/stack-on-a-budget#61]
ex:
## Static app hosting
_A short description here_

**Comment by 255kb** [comment]
hi good idea, but below service names, or categories names ?

**Comment by clement-jacquet** [comment]
Categories names, my bad

**Comment by Panca68** [comment]
pancaagusananda70@gmail.com

**Comment by clement-jacquet** [comment]
Unfortunately my english isn't good enough to do it... That's the main reason why I opened this issue!
