### ISSUE TITLE
Add New Relic

### ISSUE THREAD

**Issue by 255kb** [255kb/stack-on-a-budget#62]

**Comment by sangupta** [comment]
Plans (like NewRelic and a few others) are free for first month/first 3-months. 

Would such plans and services qualify to be in this list - considering anyone bootstrapping might not be able to break-even or get funding in such a short time?

**Comment by 255kb** [comment]
New Relic does not have a permanent free plan anymore?
Otherwise no it does not qualify

**Comment by 255kb** [comment]
Just checked, there is no free tier anymore.will add it to the wiki
