### ISSUE TITLE
Split sections into separate files

### ISSUE THREAD

**Issue by tpluscode** [255kb/stack-on-a-budget#67]
I think that the list will quickly get out of hand. Howe about splitting each section into a separate file and leaving only the table of contents in the main readme?

**Comment by 255kb** [comment]
you are right, I already thought about it,
I will probably do that in the coming days ;)

**Comment by sangupta** [comment]
@255kb - I can help split them up - the file is not too large at this point. Let me know.

**Comment by 255kb** [comment]
@sangupta wow, I am sorry I just finished splitting the files 1mn ago...

**Comment by sangupta** [comment]
@255kb No worries... it was my bad.

**Comment by 255kb** [comment]
@sangupta still it is sad to see work being trashed, thanks for your understanding 👍

**Comment by sangupta** [comment]
@255kb nah - till things are getting done... no one should mind.

BTW - do you need help in clearing up the conflicts with currently open PRs ?

**Comment by 255kb** [comment]
@sangupta That would be great, I have not a lot of time these days, and christmas is coming, it will be even harder ><
Do you need any authorization? 
Also, don't worry not everything has to be merged tonight ;) And I still want to be sure that everything is properly described

**Comment by sangupta** [comment]
@255kb You can mark issues to me and I will raise a PR so that you can run a review.

Or if you wish to grant me write access - I can them tomorrow and then you run review on HEAD.

**Comment by tpluscode** [comment]
Actually, I imagined that the service names would stay in the main readme too as links. Good idea? Bad?

**Comment by 255kb** [comment]
not a bad idea
I am using a VS Code plugin that automatically create table of contents, but not accross files, so I did not take time to do this!

**Comment by 255kb** [comment]
created an issue #102

**Comment by tpluscode** [comment]
I see. Wouldn't have been that much work given that there already was a ToC assembled

True though, that managing it manually isn't perfect

**Comment by 255kb** [comment]
yeah I will take it back from the previous version ;)
