### ISSUE TITLE
Logging Services

### ISSUE THREAD

**Issue by Lusitaniae** [255kb/stack-on-a-budget#73]
Loggly seems a good starting point.
Free plan includes 200 MB of data per day / 7 day retention.

https://www.loggly.com/plans-and-pricing/

**Comment by lukapusic** [comment]
+1

Another one is Logentries (Free tier: Send up to 5GB/month, 7 day Retention)
https://logentries.com

**Comment by lukapusic** [comment]
Logging proposed with pull request: https://github.com/255kb/stack-on-a-budget/pull/76

**Comment by lostintangent** [comment]
I added another logging provider (*Azure Application Insights*) via #130.

Presumably, this issue could also be closed now that the logging section is getting nicely populated?

**Comment by 255kb** [comment]
Thanks for all your contrib! I will close this now as everything has been or will be added.
