### ISSUE TITLE
Add Azure 

### ISSUE THREAD

**Issue by jlian** [255kb/stack-on-a-budget#75]
For example Azure App Service has a free tier 

https://azure.microsoft.com/pricing/details/app-service/ 

Product page https://azure.microsoft.com/services/app-service/

**Comment by matknapp** [comment]
There's also Microsoft Bizspark that can give users $150/month free if you qualify. Better if you plan on starting a business, over a hobby.

https://azure.microsoft.com/en-us/pricing/member-offers/bizspark-startups/
