### ISSUE TITLE
Uptime Robot

### ISSUE THREAD

**Issue by umutm** [255kb/stack-on-a-budget#78]
http://uptimeroot.com
Free tier: Uptime Monitoring. 50 websites/servers can be monitored every 5 minutes.
Pros: So easy to use, supports e-mail, Twitter, Slack, HipChat, push, SMS, web-hook notifications and more.
Limitations: Monitoring location can't be customized.
Exceeding the free tier: It is needed to pay for more monitors or 1-minute monitoring intervals.

**Comment by MuriloDalRi** [comment]
It also works for keeping Heroku's free dynos from sleeping.

**Comment by rjayasin** [comment]
@umutm I think you meant to link http://uptimerobot.com/

**Comment by 255kb** [comment]
Thanks, I added the service under Monitoring category

**Comment by umutm** [comment]
@rjayasin Exactly, thanks very much.

**Comment by umutm** [comment]
@255kb Thanks very much.
