### ISSUE TITLE
Mention dply.co in excluded services

### ISSUE THREAD

**Issue by skytreader** [255kb/stack-on-a-budget#79]
I was originally going to PR for the inclusion of dply.co but then checked the contributor's guide. Seeing that Sendgrid's free tier of 30 days has not been included, I decided against making the PR; dply.co's free tier is a mere two hours.

But could we at least give dply.co a mention in the wiki? (I don't think you could PR to wikis though, so making this request.)

[About dply.co](https://dply.co/how) / [Hacker News discussion](https://news.ycombinator.com/item?id=13030603)

**Comment by 255kb** [comment]
Great little service, but yes, maybe too short to really use it outside the testing/prototyping context. I will add this in the wiki. 
Thanks!
