### ISSUE TITLE
Let's Encrypt 90 day "limitation"

### ISSUE THREAD

**Issue by jduncanator** [255kb/stack-on-a-budget#9]
Due to the way Let's Encrypt is designed to work, it is not appropriate (or applicable) to label the 90 day certificate expiration as a "limitation". Let's Encrypt is designed to be automated. Beyond automation, 90 days is generally [a](https://community.letsencrypt.org/t/pros-and-cons-of-90-day-certificate-lifetimes/4621) [well](https://www.globalsign.com/en/blog/advantages-of-short-lived-certificates/) [accepted](http://www.w2spconf.com/2012/papers/w2sp12-final9.pdf) validity period for certificates.

I would recommend removing the 90 day limit from the limitations section of Let's Encrypt

**Comment by 255kb** [comment]
Thanks for the insights. I will let this in the limitations but insist on automation, so it looks like a "normal" limitation :)
